// <auto-generated />
using System;
using Data.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BillNumber")
                        .HasColumnType("integer");

                    b.Property<string>("CasherId")
                        .HasColumnType("text");

                    b.Property<string>("Coupon")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("Discount")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTakeAway")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemMissingReason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CasherId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Data.Entities.BillOrder", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.HasKey("OrderId", "BillId");

                    b.HasIndex("BillId");

                    b.ToTable("BillOrders");
                });

            modelBuilder.Entity("Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b1"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8972),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8974),
                            Description = "Cà phê truyền thống",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b2"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8977),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8977),
                            Description = "Cà phê ép máy",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b3"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8980),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8981),
                            Description = "Cà phê đặc biệt",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b4"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8985),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8986),
                            Description = "Nước ép",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b5"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8989),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8990),
                            Description = "Sinh tố",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b6"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8992),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8993),
                            Description = "Trà sữa",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b7"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8995),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8995),
                            Description = "Trà nóng",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b8"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8998),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8998),
                            Description = "Trà trà",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b9"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9001),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9002),
                            Description = "Ăn vặt",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Data.Entities.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb22e2ea-0305-4778-a129-f400e6a64447"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8893),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8899),
                            Description = "Tầng 1",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("eb22e2ea-0305-4778-a129-f400e6a64445"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8914),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(8915),
                            Description = "Tầng 2",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Data.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Available")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16d3154f-b5e8-4b00-9262-a4215b43f6ee"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b1"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9042),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9043),
                            IsDeleted = false,
                            Name = "Cà phê đen phin",
                            Price = 12000.0
                        },
                        new
                        {
                            Id = new Guid("26d3154f-b5e8-4b00-9262-a4215b43f6ee"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b1"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9047),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9047),
                            IsDeleted = false,
                            Name = "Cà phê sữa phin",
                            Price = 14000.0
                        },
                        new
                        {
                            Id = new Guid("36d3154f-b5e8-4b00-9262-a4215b43f6ee"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b1"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9051),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9051),
                            IsDeleted = false,
                            Name = "Cà phê đen đá Sài Gòn",
                            Price = 18000.0
                        },
                        new
                        {
                            Id = new Guid("46d3154f-b5e8-4b00-9262-a4215b43f6ee"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b1"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9055),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9055),
                            IsDeleted = false,
                            Name = "Cà phê sữa đá Sài Gòn",
                            Price = 20000.0
                        },
                        new
                        {
                            Id = new Guid("56d3154f-b5e8-4b00-9262-a4215b43f6ee"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b1"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9059),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9059),
                            IsDeleted = false,
                            Name = "Bạc xỉu",
                            Price = 22000.0
                        },
                        new
                        {
                            Id = new Guid("66d3154f-b5e8-4b00-9262-a4215b43f6ee"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b1"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9062),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9063),
                            IsDeleted = false,
                            Name = "Ca cao nóng - đá",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = new Guid("ff64e1d2-a0e7-40a9-9bb1-d01a19bea5b1"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b2"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9066),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9066),
                            IsDeleted = false,
                            Name = "Cà phê đen máy",
                            Price = 16000.0
                        },
                        new
                        {
                            Id = new Guid("ff64e1d2-a0e7-40a9-9bb1-d01a19bea5b2"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b2"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9070),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9070),
                            IsDeleted = false,
                            Name = "Cà phê sữa máy",
                            Price = 18000.0
                        },
                        new
                        {
                            Id = new Guid("1929dacf-d25a-4a8d-b647-c9a29d3d552b"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b3"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9146),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9147),
                            IsDeleted = false,
                            Name = "Cà phê kem trứng muối",
                            Price = 29000.0
                        },
                        new
                        {
                            Id = new Guid("2929dacf-d25a-4a8d-b647-c9a29d3d552b"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b3"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9151),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9152),
                            IsDeleted = false,
                            Name = "Cà phê cốt dừa",
                            Price = 29000.0
                        },
                        new
                        {
                            Id = new Guid("3929dacf-d25a-4a8d-b647-c9a29d3d552b"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b3"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9155),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9155),
                            IsDeleted = false,
                            Name = "Cà phê trứng",
                            Price = 29000.0
                        },
                        new
                        {
                            Id = new Guid("4929dacf-d25a-4a8d-b647-c9a29d3d552b"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b3"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9160),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9160),
                            IsDeleted = false,
                            Name = "Cappuchino",
                            Price = 29000.0
                        },
                        new
                        {
                            Id = new Guid("c3667f70-c2b7-4af9-8300-ad54c79e841a"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b4"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9163),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9164),
                            IsDeleted = false,
                            Name = "Nước ép dưa hấu",
                            Price = 22000.0
                        },
                        new
                        {
                            Id = new Guid("c3667f70-c2b7-4af9-8300-ad54c79e842a"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b4"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9167),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9168),
                            IsDeleted = false,
                            Name = "Nước ép cà rốt",
                            Price = 22000.0
                        },
                        new
                        {
                            Id = new Guid("c3667f70-c2b7-4af9-8300-ad54c79e843a"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b4"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9171),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9171),
                            IsDeleted = false,
                            Name = "Nước ép thơm",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = new Guid("c3667f70-c2b7-4af9-8300-ad54c79e844a"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b4"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9175),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9175),
                            IsDeleted = false,
                            Name = "Nước ép cam",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = new Guid("1649ec15-fcec-4368-83f9-5b16f43fee5b"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b5"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9178),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9179),
                            IsDeleted = false,
                            Name = "Sinh tố bơ",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = new Guid("2649ec15-fcec-4368-83f9-5b16f43fee5b"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b5"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9182),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9182),
                            IsDeleted = false,
                            Name = "Sinh tố bơ sầu riêng",
                            Price = 35000.0
                        },
                        new
                        {
                            Id = new Guid("3649ec15-fcec-4368-83f9-5b16f43fee5b"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b5"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9186),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9186),
                            IsDeleted = false,
                            Name = "Sinh tố xoài",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = new Guid("4649ec15-fcec-4368-83f9-5b16f43fee5b"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b5"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9190),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9190),
                            IsDeleted = false,
                            Name = "Sinh tố dâu tây",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = new Guid("d135806f-52da-434f-840b-ae253b0fbbff"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b6"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9194),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9195),
                            IsDeleted = false,
                            Name = "Trà sữa truyền thống",
                            Price = 22000.0
                        },
                        new
                        {
                            Id = new Guid("d235806f-52da-434f-840b-ae253b0fbbff"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b6"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9198),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9199),
                            IsDeleted = false,
                            Name = "Trà sữa kem trứng muối",
                            Price = 29000.0
                        },
                        new
                        {
                            Id = new Guid("d335806f-52da-434f-840b-ae253b0fbbff"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b6"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9202),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9203),
                            IsDeleted = false,
                            Name = "Trà sữa khoai môn",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = new Guid("d18ca698-10a5-42e3-b044-3bdd2e5d81bd"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b7"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9207),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9208),
                            IsDeleted = false,
                            Name = "Trà olong cúc mật ong nóng",
                            Price = 22000.0
                        },
                        new
                        {
                            Id = new Guid("d28ca698-10a5-42e3-b044-3bdd2e5d81bd"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b7"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9211),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9212),
                            IsDeleted = false,
                            Name = "Trà hoa cúc nóng",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = new Guid("d38ca698-10a5-42e3-b044-3bdd2e5d81bd"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b7"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9215),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9216),
                            IsDeleted = false,
                            Name = "Trà chanh nóng",
                            Price = 22000.0
                        },
                        new
                        {
                            Id = new Guid("5020bd91-1caf-4868-9fe5-9a1360c48321"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b8"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9219),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9219),
                            IsDeleted = false,
                            Name = "Trà chanh",
                            Price = 22000.0
                        },
                        new
                        {
                            Id = new Guid("5020bd91-1caf-4868-9fe5-9a1360c48322"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b8"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9227),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9228),
                            IsDeleted = false,
                            Name = "Trà chanh dây",
                            Price = 22000.0
                        },
                        new
                        {
                            Id = new Guid("5020bd91-1caf-4868-9fe5-9a1360c48323"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b8"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9232),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9232),
                            IsDeleted = false,
                            Name = "Trà lipton nóng - đá",
                            Price = 20000.0
                        },
                        new
                        {
                            Id = new Guid("5020bd91-1caf-4868-9fe5-9a1360c48324"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b8"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9235),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9236),
                            IsDeleted = false,
                            Name = "Trà gừng nóng - đá",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = new Guid("5020bd91-1caf-4868-9fe5-9a1360c48325"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b8"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9239),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9239),
                            IsDeleted = false,
                            Name = "Trà đào cam xả",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = new Guid("5020bd91-1caf-4868-9fe5-9a1360c48326"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b8"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9243),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9243),
                            IsDeleted = false,
                            Name = "Trà vải",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = new Guid("5020bd91-1caf-4868-9fe5-9a1360c48327"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b8"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9246),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9246),
                            IsDeleted = false,
                            Name = "Trà sen macchiato",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = new Guid("5020bd91-1caf-4868-9fe5-9a1360c48328"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b8"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9251),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9251),
                            IsDeleted = false,
                            Name = "Trà đen macchiato",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = new Guid("5020bd91-1caf-4868-9fe5-9a1360c48329"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b8"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9254),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9255),
                            IsDeleted = false,
                            Name = "Trà dâu",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = new Guid("1afeafff-f9d3-4a88-8a03-950482af826f"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b9"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9261),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9262),
                            IsDeleted = false,
                            Name = "Bắp rang bơ",
                            Price = 15000.0
                        },
                        new
                        {
                            Id = new Guid("2afeafff-f9d3-4a88-8a03-950482af826f"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b9"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9269),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9270),
                            IsDeleted = false,
                            Name = "Bắp rang bơ caramel",
                            Price = 20000.0
                        },
                        new
                        {
                            Id = new Guid("3afeafff-f9d3-4a88-8a03-950482af826f"),
                            Available = true,
                            CategoryId = new Guid("4f16c29d-f0dd-4c41-8481-48f32d4cd5b9"),
                            DateCreated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9273),
                            DateUpdated = new DateTime(2022, 10, 17, 20, 37, 12, 665, DateTimeKind.Utc).AddTicks(9273),
                            IsDeleted = false,
                            Name = "Bắp rang bơ phô mai",
                            Price = 20000.0
                        });
                });

            modelBuilder.Entity("Data.Entities.ItemImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemImages");
                });

            modelBuilder.Entity("Data.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<bool>("IsCheckout")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMissing")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserRejectedId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TableId");

                    b.HasIndex("UserRejectedId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Data.Entities.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FinalQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("MissingReason")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Data.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Key = "ORDER_RECEIVER",
                            Value = "[\"BARTENDER\"]"
                        });
                });

            modelBuilder.Entity("Data.Entities.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rotation")
                        .HasColumnType("integer");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ADMIN",
                            ConcurrencyStamp = "ADMIN",
                            Name = "ADMIN",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "BARTENDER",
                            ConcurrencyStamp = "BARTENDER",
                            Name = "BARTENDER",
                            NormalizedName = "BARTENDER"
                        },
                        new
                        {
                            Id = "CUSTOMER",
                            ConcurrencyStamp = "CUSTOMER",
                            Name = "CUSTOMER",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "EMPLOYEE",
                            ConcurrencyStamp = "EMPLOYEE",
                            Name = "EMPLOYEE",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = "CASHER",
                            ConcurrencyStamp = "CASHER",
                            Name = "CASHER",
                            NormalizedName = "CASHER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Bill", b =>
                {
                    b.HasOne("Data.Entities.User", "Casher")
                        .WithMany()
                        .HasForeignKey("CasherId");

                    b.HasOne("Data.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Casher");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Data.Entities.BillOrder", b =>
                {
                    b.HasOne("Data.Entities.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Data.Entities.Item", b =>
                {
                    b.HasOne("Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Data.Entities.ItemImage", b =>
                {
                    b.HasOne("Data.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Data.Entities.Order", b =>
                {
                    b.HasOne("Data.Entities.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Data.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");

                    b.HasOne("Data.Entities.User", "UserRejected")
                        .WithMany()
                        .HasForeignKey("UserRejectedId");

                    b.Navigation("Employee");

                    b.Navigation("Table");

                    b.Navigation("UserRejected");
                });

            modelBuilder.Entity("Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("Data.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Data.Entities.Table", b =>
                {
                    b.HasOne("Data.Entities.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
